export const START_TRIP_DISTANCE_METERS = 20
export const OFF_ROUTE_DISTANCE_METERS = 20
export const AUTO_COMPLETE_DISTANCE_METERS = 10
export const REPORT_CONFIRM_DISTANCE_METERS = 15
export const REPORT_CONFIRM_DISMISS_MS = 8000
