# dev
FROM node:22-bookworm-slim
WORKDIR /app

RUN apt-get update \
 && apt-get install -y openssl ca-certificates \
 && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci

COPY tsconfig*.json ./
COPY prisma ./prisma
COPY src ./src

RUN npm run prisma:generate

ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "dev"]
