-- AlterTable
ALTER TABLE "OverallStat" ADD COLUMN     "longestKilometer" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "longestTime" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "pathsCreated" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalKilometers" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalTime" DOUBLE PRECISION NOT NULL DEFAULT 0;
